* README

Haoyang's GNU Emacs configuration, the n-th iteration.

Ideas are from [[http://eschulte.me/emacs24-starter-kit/#installation][Emacs Starter Kit]], [[http://pages.sachachua.com/.emacs.d/Sacha.html][Sache Chua's config]], [[https://sam217pa.github.io/2016/09/02/how-to-build-your-own-spacemacs/][Sam217's blog]] and my desire to use Org-mode as an effective project management tool.

** Principles

- Effective navigation (hence Evil-mode)
- Easy to read and edit (hence use-package, visual-line-mode)
- Simlified shortcuts
- Self documenting (hence which-key)
  
* Basic information

#+BEGIN_SRC emacs-lisp
(setq user-full-name "Haoyang Xu")
(setq user-mail-address "github@expoundite.net")
#+END_SRC

* Behaviour

A few sensible choices that affect the global behaviour of Emacs:

#+BEGIN_SRC emacs-lisp
  (setq delete-old-versions -1 ); delete excess backup versions silently
  (setq version-control t ); use version control
  (setq vc-make-backup-files t ); make backups file even when in version controlled dir
  (setq backup-directory-alist `(("." . "~/.emacs.d/backups")) ) ; which directory to put backups file
  (setq vc-follow-symlinks t )       ; don't ask for confirmation when opening symlinked file
  (setq auto-save-file-name-transforms '((".*" "~/.emacs.d/auto-save-list/" t)) ) ;transform backups file name
  (setq inhibit-startup-screen t ); inhibit useless and old-school startup screen
  (setq ring-bell-function 'ignore ); silent bell when you make a mistake
  (setq coding-system-for-read 'utf-8 ); use utf-8 by default
  (setq coding-system-for-write 'utf-8 )
  (setq sentence-end-double-space nil); sentence SHOULD end with only a point.
  (setq default-fill-column 80); toggle wrapping text at the 80th character
  (setq initial-scratch-message "Welcome in Emacs") ; print a default message in the empty scratch buffer opened at startup
  (tool-bar-mode -1)
  (menu-bar-mode -1)
  (scroll-bar-mode 0)
  (setq inhibit-startup-screen 1)
  (setq org-hide-emphasis-markers t)

#+END_SRC

* Dependencies

This config requires Org-mode newer than 8.0, and Emacs > 23.

#+BEGIN_SRC emacs-lisp
  (when (version<= emacs-version "24")
  (message "This config requires at least Emacs 24, please upgrade."))

#+END_SRC

This config utilizes Emacs' package support. Some additional repositories are added.

#+BEGIN_SRC emacs-lisp
(setq package-archives '(("gnu" . "http://elpa.gnu.org/packages/")
			 ("melpa" . "https://melpa.org/packages/")
			 ("marmalade" . "https://marmalade-repo.org/packages/")
			 ("org" . "http://orgmode.org/elpa/")))
#+END_SRC

Bootstrap =use-package=.

#+BEGIN_SRC emacs-lisp
  (unless (package-installed-p 'use-package) ; unless it is already installed
    (package-refresh-contents) ; updage packages archive
    (package-install 'use-package)) ; and install the most recent version of use-package

  (require 'use-package)
#+END_SRC

* Evil-mode
  Evil-mode allows vim-style modes and keybindings in Emacs. Now you have the best editor in the best Lisp Machine.

  #+BEGIN_SRC emacs-lisp
    (use-package evil :ensure t
                 :config
                 (evil-mode 1))
  #+END_SRC
  
* Org-mode
  #+BEGIN_SRC emacs-lisp
    (use-package org :ensure t)
    (use-package org-plus-contrib :ensure t)
  #+END_SRC
